import 'package:flutter/material.dart';
String baseUrl = "https://rstask.wiremockapi.cloud";
const Color colorPrimary = Color(0xFFD1D1D1);
const Color colorPrimaryLight = Color(0xFFB4ABAA);
const Color colorPrimaryDark = Color(0xFF796E6D);
const Color colorBlack = Color(0xFF121212);
const Color colorGrey = Color(0xFFCBCBCB);
const Color colorAccent = Color(0xFF54ADA2);
const Color colorGreen = Color(0xFF6DC65d);
const Color colorGreenPrimary = Color(0xFFA3C49D);
const Color colorGreenAccent = Color(0xFFACDBA3);
const Color colorRed = Color(0xFFCD2016);
const Color colorWhite = Color(0xFFFFFFFF);
const Color colorWhiteAccent = Color(0xFFE0E9DE);
const Color colorOrange = Color(0xFFEF993D);
const Color colorGreyAccent = Color(0xffEEF1E2);
const Color colorDeepGreen = Color(0xff44C991);
const Color colorYellow100 = Color(0xffFBFCEF);